### ISSUE TITLE
["Bug"] BungeeCord cannot enter the server across servers

### ISSUE THREAD

**Issue by 1766141426** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#47]
![9f89e62026ff355d0ddacae3bb650550](https://github.com/user-attachments/assets/9cb56a99-460f-4c56-8920-d74eb2de7a41)

Using BungeeCord to cross servers, the server prompts that this can't enter the server, and I checked that the mod is caused by MrCrayfish, can the author fix it?

使用 BungeeCord 端跨服，进服提示这个进不去服务器，排查了mod 是MrCrayfish 导致的，作者大大可以修复下吗

**Comment by MrCrayfish** [comment]
BungeeCord doesn't understand the additional payloads that are sent during the handshake phase (custom recipe types and configs are sent from the server to client when a player logs into the game). You would need to write some sort of plugin for BungeeCord to forward those additional payloads. This is a pitfall of BungeeCord, and hence cannot be fixed in my mod.
